# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  body_listener: true
  view:
    view_response_listener:  true
  serializer:
    serialize_null: true
#  exception:
#    exception_controller: 'fos_rest.exception.controller:showAction'
#    codes:
#      Doctrine\ORM\EntityNotFoundException: 404
  format_listener:
    enabled: true
    rules:
      - { path: ^/api, prefer_extension: false, fallback_format: json, priorities: [ json ] }
      - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: html, prefer_extension: true }